13th external api
ekateriniy/test-guru pull request #14
Opened 2022-04-22 11:24 UTC by ekateriniy

2022-04-22 20:30 UTC, VidgarVii requested changes

2022-04-22 20:30 UTC, VidgarVii commented on Gemfile
> +gem 'dotenv-rails', groups: [:development, :test]
пару строк ниже такая группа уже объявлена. Устанавливай гем лучше там

2022-04-22 20:30 UTC, VidgarVii commented on app/controllers/admin/gists_controller.rb
> +
лишний отступ
пользуйся рубокопом

2022-04-22 20:30 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    if @gist[:html_url]
1 у тебя сейчас логика размазана м/у сервисом и контроллером. Сильная логическая связь м/у контроллером и сервисом. Т.е. ты просто часть задачи возложил на контроллер. Это плохо. 
Контроллер просто делегат. Сам он ни чего не делает. Он только знает кого надо дёргать, чтобы выполнилось какая-то задача.
Суть создания отдельного класса - вынести в него часть логики и скрыть детали реализации. Логика определения успешности создания Гиста тоже лучше оставить в сервис и не мучить дополнительной сложностью контроллер. 

есть стандартный принятый подход для сервисов.
```
result = GistService.new(@test_passage.current_question).create_gist
if result.success?
  ...
   result.url
   result.id
  ...
else
end
```

2022-04-22 20:30 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +      flash_options = { notice: "#{t('.success_html')} #{view_context.link_to 'Gist', @gist[:html_url]}" }
2 Метод call должен вернуть такой объект, который содержит все нужные методы и данные. И хорошо если всё это будет прописано в явном виде. Сейчас же не понятно от куда берутся методы такие как html_url. 
Для создания такого объекта можно воспользоваться Struct 
Минус твоего подхода в том, что если придётся менять гем, то придётся исправлять код в разных местах проекта. А класс GistQuestionService служит своего рода адаптером над октокит. Его задача не только создавать гист. Это он вообще делегирует гему октокит. А скрыть сложность создания гиста и предоставить общий интерфейс, который не зависит от хттп клиента. И если придётся менять этот хттп клиент, то рефакторигну подвергнется только сервис  GistQuestionService

2022-04-22 20:30 UTC, VidgarVii commented on app/models/gist.rb
> +    question.body.length > 25 ? question.body[0..26] : question.body
здесь лучше использовать хелпер `truncate` - [вот небольшой пост про него](https://makandracards.com/makandra/53287-heads-up-rails-offers-two-similar-means-for-text-truncation)

2022-04-22 20:30 UTC, VidgarVii commented on app/models/gist.rb
> +    url.split('.com/')[1]
https://ruby-doc.org/stdlib-2.7.1/libdoc/uri/rdoc/URI.html

2022-04-22 20:30 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
еще можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```
уменьшит потребление памяти и выглядит лучше

2022-04-22 20:30 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
установка "нил" в аргументах - это возможно не лучшее решение
я бы для такого случая порекомендовал вариант установки дефолта, к примеру, такой:
```ruby
def initialize(question, client = default_client)
  ...
  @client = client
end
```
далее можно определить в методе `default_client` "дефолтного клиента"

```ruby
private

def default_client
  Octokit::Client.new(access_token: GITHUB_GIST_TOKEN)
end
```

2022-04-23 10:09 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  before_action :set_test_passage, on: %i[show result update gist]
у этого контроллера не должно быть экшена gist

2022-04-23 10:09 UTC, VidgarVii commented on app/helpers/questions_helper.rb
>    end
```ruby 
action = question.persisted? ? 'Edit' : 'Create'
```

2022-04-23 10:09 UTC, VidgarVii commented on app/models/gist.rb
> +    URI.split(url)[5].split('/')[-1]
стало еще хуже. Прочитай документацию как пользоваться объектом URI

2022-04-23 10:09 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +      !:url.nil?
url.present?

2022-04-23 13:26 UTC, ekateriniy commented on app/models/gist.rb
> +    URI.split(url)[5].split('/')[-1]
@VidgarVii я прочитала документацию, спасибо. Но все же не совсем понимаю: что в контексте этой самой документации делать? URI.path[1..-1] или какой еще способ?

2022-04-24 15:49 UTC, merged